#必须要加空格，空格不能省略
server:
  port: 8081
  servlet:
    context-path: /yml


user:
  username: tom
  address: 广州
  favorites:
    - 足球
    - 篮球
    - 乒乓球
  dog:
    - name: 小黑
      color: 黑色
    - name: 小白
      color: 白色
